# Why python for data analysis, machine learning?
There are lots of reasons that we want to use python for doing data science. It is certainly one of the younger programming languages used in the data science ecosystem (compared to say R and SAS) but it is used just as frequently for analysis as SAS and R. Having a good foundation in python and R, (and SAS or SPSS) should be a *must* for **every data scientist** and machine learning enthusiast. 

Here is a latex equation $\lambda=5$ 

In this course, python allows for an open source method of performing machine learning that runs from just about any machine. So let's start with looking at Numpy and Pandas pachages for analyzing data. 

With that in mind, let's go over the following:
- Numpy matrices
- Simple operations on arrays and matrices
- Indexing with numpy
- Pandas for tabular data
- Representing categorical data (discussion point)

In [1]:
import sys
import numpy as np

print(sys.version)
print(np.__version__)

3.8.16 (default, Mar  1 2023, 21:18:45) 
[Clang 14.0.6 ]
1.23.5


In [2]:
x = np.random.rand(5,3)
x

array([[0.89162028, 0.97369146, 0.84477866],
       [0.82200745, 0.04894302, 0.34575096],
       [0.96169398, 0.22250412, 0.94717825],
       [0.85062942, 0.64487153, 0.1689844 ],
       [0.27999124, 0.78141442, 0.05305638]])

In [3]:
x.shape

(5, 3)

In [4]:
x.dtype

dtype('float64')

In [5]:
# will this work?
y = np.random.rand(3,4)
z = x*y
z

ValueError: operands could not be broadcast together with shapes (5,3) (3,4) 

In [6]:
# we can designate what matrix multiplication is directly using objects
z = np.dot(x,y)
z

array([[1.62519216, 1.61165567, 2.0642909 , 1.47188586],
       [0.81208096, 1.00549686, 0.82198292, 0.44786103],
       [1.52738965, 1.53879288, 1.44356732, 0.99309143],
       [0.84452074, 1.08814595, 1.31620868, 0.78637785],
       [0.45454204, 0.50838927, 0.98475922, 0.68175702]])

In [7]:
# or we can use the overloaded matrix multiplication operator
z = x @ y
z

array([[1.62519216, 1.61165567, 2.0642909 , 1.47188586],
       [0.81208096, 1.00549686, 0.82198292, 0.44786103],
       [1.52738965, 1.53879288, 1.44356732, 0.99309143],
       [0.84452074, 1.08814595, 1.31620868, 0.78637785],
       [0.45454204, 0.50838927, 0.98475922, 0.68175702]])

# Indexing

In [8]:
x1 = np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])
x1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
for row in range(x1.shape[0]):
    print(x1[row,1])

In [ ]:
print(x1[:,1])
print(x1[:,1]>3)
# slicing
print(x1[ x1[:,1]>3 ])

In [ ]:
x2 = np.array(range(10))
print(x2)
x2.shape

In [ ]:
idx = x2>5
print(idx)
print(x2[idx])

In [ ]:
x2[x2>5] # rows of x2 where x2 is greater than 5

# Named columns
So what if we have a matrix of data where each row is some observation of features and the feature values are represented in each column?

In [ ]:
col_names = ['temperature','time','day']
data = np.array([[64,2100,1],
                 [50,2200,4],
                 [48,2300,3],
                 [34,0,   2],
                 [30,100, 5]])
data

In [ ]:
data2 = data[data[:,1]>1500]
data2

In [ ]:
# pandas to the rescue
import pandas as pd
print(pd.__version__)

df = pd.DataFrame(data,columns=col_names)
df

In [ ]:
# can always access the backend numpy with .values
print(type(df.to_numpy()))
df.to_numpy()

In [ ]:
df[df.time>1500]

In [ ]:
# lets get a description of the data
df.info()

In [ ]:
df.day[df.day==1] = 'Mon'
df

In [ ]:
# there is almost always a more efficient built in pandas function
df.day.replace(to_replace=range(7),
               value=['Su','Mon','Tues','Wed','Th','Fri','Sat'],
               inplace=True)
df

In [ ]:
# notice how the type of the column has changed to an object "categorical"
df.info()

In [ ]:
# one hot encoding example
pd.get_dummies(df.day)

# Some Pandas Syntax

In [ ]:
# slicing into a pandas dataframe
print(df.day)
print(df['day'])
df[['day','temperature']]

In [ ]:
print(df.day[2]) # print the value
print(df.day[2:]) # print as pandas series

In [ ]:
# index location
df.iloc[3:]

In [ ]:
df.iloc[3:][['day','temperature']]

In [ ]:
df[['day','temperature']].iloc[3:]

In [ ]:
df.mean(numeric_only=True)

In [ ]:
df.std(numeric_only=True)

In [ ]:
df.mean(numeric_only=True)/df.std(numeric_only=True)

In [ ]:
df.time.unique()

# Pandas Block Manager
Let's take a look at some important points from the following post:
 - https://uwekorn.com/2020/05/24/the-one-pandas-internal.html

This is the pandas BlockManager, which tries to group internal structures together to make things fast:
<img src="https://uwekorn.com/images/pd-df-perception.002.png" width=200 height=200 />

In [ ]:
df

In [ ]:
print(df._data.nblocks)
df._data

## Advantages and disadvantages:
This can speed up operations because it inhenertly can apply operations along columns in a single pass over the data (like sums, etc.) and therefore is using c++ for much of the heavy lifting.

But, **it might be bad** when you are adding columns to the data because it can trigger consolidation of columns, which means copying over data in numpy to creata new matrix. The slow down also doesn't show up until a needed column is accessed (lazy data copying). Let's do an example from:  https://uwekorn.com/2020/05/24/the-one-pandas-internal.html

**Block consolidation is triggered after 100 blocks of data are reached.**

In [ ]:
# we will start with a 2 column dataframe
# one column is an int and the other a float
# becasue there are two datatypes this has two blocks
df_example = pd.DataFrame({
    'int64': np.arange(1024 * 1024, dtype=np.int64),
    'float64': np.arange(1024 * 1024, dtype=np.float64),
})
df_example

In [ ]:
%%time 

# but now lets start to add columns one by one
# to be fast, pandas adds each as a new block 
# so we will have 99 blocks (2+97 new ones)
for i in range(96):
    df_example[f'new_{i}'] = df_example['int64'].to_numpy()
    
print(df_example._data.nblocks)
df_example

In [ ]:
%time df_example['dummy_name5'] = df_example['int64'].to_numpy() # copy over some new columns
print('Number of blocks in data:',df_example._data.nblocks)

# force consolidation 
%time df_example = df_example.reindex()

%time df_example['dummy_name6'] = df_example['int64'].to_numpy() # copy over some new columns
print('Number of blocks in data:',df_example._data.nblocks)


In [ ]:
df_example.info()