# Why python for data analysis, machine learning?
There are lots of reasons that we want to use python for doing data science. It is certainly one of the younger programming languages used in the data science ecosystem (compared to say R and SAS) but it is used just as frequently for analysis as SAS and R. Having a good foundation in python, R, and SAS should be a *must* for **every data scientist** and machine learning enthusiast. 

In this course, python allows for an open source method of performing machine learning that runs from just about any machine. So let's start with looking at Numpy and Pandas pachages for analyzing data. 

With that in mind, let's go over the following:
- Numpy matrices
- Simple operations on arrays and matrices
- Indexing with numpy
- Pandas for tabular data
- Representing categorical data (discussion point)

In [1]:
import sys
import numpy as np

print(sys.version)
print(np.__version__)

3.5.4 |Continuum Analytics, Inc.| (default, Aug 14 2017, 12:43:10) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)]
1.13.1


In [2]:
x = np.random.rand(5,3)
x

array([[ 0.71123289,  0.02519477,  0.97639939],
       [ 0.71015964,  0.54387223,  0.54625691],
       [ 0.83366462,  0.38765327,  0.28341864],
       [ 0.1430888 ,  0.49790126,  0.22830317],
       [ 0.38527387,  0.50612705,  0.65231672]])

In [3]:
x.shape

(5, 3)

In [5]:
x.dtype

dtype('float64')

In [6]:
y = np.random.rand(3,4)
z = x*y
z

ValueError: operands could not be broadcast together with shapes (5,3) (3,4) 

In [7]:
z = np.dot(x,y)
z

array([[ 1.08966006,  0.98434136,  0.53632961,  1.17053715],
       [ 0.91356761,  1.12450633,  0.6075623 ,  1.0364879 ],
       [ 0.90606393,  0.82077882,  0.58884151,  0.73276967],
       [ 0.2483236 ,  0.6673954 ,  0.24593795,  0.53561538],
       [ 0.6599712 ,  1.07203995,  0.4429758 ,  1.02276153]])

In [8]:
z = x @ y
z

array([[ 1.08966006,  0.98434136,  0.53632961,  1.17053715],
       [ 0.91356761,  1.12450633,  0.6075623 ,  1.0364879 ],
       [ 0.90606393,  0.82077882,  0.58884151,  0.73276967],
       [ 0.2483236 ,  0.6673954 ,  0.24593795,  0.53561538],
       [ 0.6599712 ,  1.07203995,  0.4429758 ,  1.02276153]])

# Indexing

In [9]:
x1 = np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])
x1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
for row in range(x1.shape[0]):
    print(x1[row,1])

2
5
8


In [11]:
x1[:,1]

array([2, 5, 8])

In [12]:
x1[:,1]>3

array([False,  True,  True], dtype=bool)

In [13]:
x1[ x1[:,1]>3 ]

array([[4, 5, 6],
       [7, 8, 9]])

In [14]:
x2 = np.array(range(10))
x2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
x2.shape

(10,)

In [16]:
idx = x2>5
idx

array([False, False, False, False, False, False,  True,  True,  True,  True], dtype=bool)

In [17]:
x2[idx]

array([6, 7, 8, 9])

In [18]:
x2[x2>5]

array([6, 7, 8, 9])

# Named columns
So what if we have a matrix of data where each row is some observation of features and the feature values are represented in each column?

In [19]:
col_names = ['temperature','time','day']
data = np.array([[64,2100,1],
                 [50,2200,1],
                 [48,2300,1],
                 [34,0,   2],
                 [30,100, 5]])
data

array([[  64, 2100,    1],
       [  50, 2200,    1],
       [  48, 2300,    1],
       [  34,    0,    2],
       [  30,  100,    5]])

In [20]:
data2 = data[data[:,1]>1500]
data2

array([[  64, 2100,    1],
       [  50, 2200,    1],
       [  48, 2300,    1]])

In [21]:
# pandas to the rescue
import pandas as pd

df = pd.DataFrame(data,columns=col_names)
df

temperature  time  day
0           64  2100    1
1           50  2200    1
2           48  2300    1
3           34     0    2
4           30   100    5

In [24]:
df[df.time>1500]

temperature  time  day
0           64  2100    1
1           50  2200    1
2           48  2300    1

In [25]:
# lets get a description of the data
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
temperature    5 non-null int64
time           5 non-null int64
day            5 non-null int64
dtypes: int64(3)
memory usage: 200.0 bytes


In [26]:
df.day[df.day==1] = 'Mon'
df

temperature  time  day
0           64  2100  Mon
1           50  2200  Mon
2           48  2300  Mon
3           34     0    2
4           30   100    5

In [27]:
# there is almost always a more efficient built in pandas function
df.day.replace(to_replace=range(7),
               value=['Su','Mon','Tues','Wed','Th','Fri','Sat'],
               inplace=True)
df

temperature  time   day
0           64  2100   Mon
1           50  2200   Mon
2           48  2300   Mon
3           34     0  Tues
4           30   100   Fri

In [28]:
# notice how the type of the column has changed to an object "categorical"
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
temperature    5 non-null int64
time           5 non-null int64
day            5 non-null object
dtypes: int64(2), object(1)
memory usage: 200.0+ bytes


In [29]:
# one hot encoding example
pd.get_dummies(df.day)

Fri  Mon  Tues
0    0    1     0
1    0    1     0
2    0    1     0
3    0    0     1
4    1    0     0