In [1]:
#  Ebnable HTML/CSS 
from IPython.core.display import HTML
HTML("<link href='https://fonts.googleapis.com/css?family=Passion+One' rel='stylesheet' type='text/css'><style>div.attn { font-family: 'Helvetica Neue'; font-size: 30px; line-height: 40px; color: #FFFFFF; text-align: center; margin: 30px 0; border-width: 10px 0; border-style: solid; border-color: #5AAAAA; padding: 30px 0; background-color: #DDDDFF; }hr { border: 0; background-color: #ffffff; border-top: 1px solid black; }hr.major { border-top: 10px solid #5AAA5A; }hr.minor { border: none; background-color: #ffffff; border-top: 5px dotted #CC3333; }div.bubble { width: 65%; padding: 20px; background: #DDDDDD; border-radius: 15px; margin: 0 auto; font-style: italic; color: #f00; }em { color: #AAA; }div.c1{visibility:hidden;margin:0;height:0;}div.note{color:red;}</style>")

___
Enter Team Member Names here (double click to edit):

- Name 1: Juliana Antonio
- Name 2: Chuanqi Deng
- Name 3: Xiaona Hang


# In Class Assignment One
In the following assignment you will be asked to fill in python code and derivations for a number of different problems. Please read all instructions carefully and turn in the rendered notebook (or HTML of the rendered notebook)  before the end of class (or right after class). The initial portion of this notebook is given before class and the remainder is given during class. Please answer the initial questions before class, to the best of your ability. Once class has started you may rework your answers as a team for the initial part of the assignment. 

<a id="top"></a>
## Contents
* <a href="#Loading">Loading the Data</a>
* <a href="#linearnumpy">Linear Regression</a>
* <a href="#sklearn">Using Scikit Learn for Regression</a>
* <a href="#classification">Linear Classification</a>

________________________________________________________________________________________________________

<a id="Loading"></a>
<a href="#top">Back to Top</a>
## Loading the Data
Please run the following code to read in the "diabetes" dataset from sklearn's data loading module. 

This will load the data into the variable `ds`. `ds` is a `bunch` object with fields like `ds.data` and `ds.target`. The field `ds.data` is a numpy matrix of the continuous features in the dataset. **The object is not a pandas dataframe. It is a numpy matrix.** Each row is a set of observed instances, each column is a different feature. It also has a field called `ds.target` that is a continuous value we are trying to predict. Each entry in `ds.target` is a label for each row of the `ds.data` matrix. 

In [2]:
from sklearn.datasets import load_diabetes
import numpy as np
from __future__ import print_function


ds = load_diabetes()

# this holds the continuous feature data
# because ds.data is a matrix, there are some special properties we can access (like 'shape')
print('features shape:', ds.data.shape, 'format is:', ('rows','columns')) # there are 442 instances and 10 features per instance
print('range of target:', np.min(ds.target),np.max(ds.target))

features shape: (442, 10) format is: ('rows', 'columns')
range of target: 25.0 346.0


In [3]:
from pprint import pprint

# we can set the fields inside of ds and set them to new variables in python
pprint(ds.data) # prints out elements of the matrix
pprint(ds.target) # prints the vector (all 442 items)

array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990749, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06833155, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286131, -0.02593034],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04688253,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452873, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00422151,  0.00306441]])
array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
        69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
        68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
        87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
       259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
       128.,  52.,  37

________________________________________________________________________________________________________
<a id="linearnumpy"></a>
<a href="#top">Back to Top</a>
## Using Linear Regression 
In the videos, we derived the formula for calculating the optimal values of the regression weights (you must be connected to the internet for this equation to show up properly):

$$ w = (X^TX)^{-1}X^Ty $$

where $X$ is the matrix of values with a bias column of ones appended onto it. For the diabetes dataset one could construct this $X$ matrix by stacking a column of ones onto the `ds.data` matrix. 

$$ X=\begin{bmatrix}
         & \vdots &        &  1 \\
        \dotsb & \text{ds.data} & \dotsb &  \vdots\\
         & \vdots &         &  1\\
     \end{bmatrix}
$$

**Question 1:** For the diabetes dataset, how many elements will the vector $w$ contain?

In [4]:
# Enter your answer here (or write code to calculate it)

num_features = ds.data.shape[1]

# Number of elements in the vector w (N + 1)
num_elements_w = num_features + 1

print("Number of elements in the vector w:", num_elements_w)

Number of elements in the vector w: 11


________________________________________________________________________________________________________

**Exercise 1:** In the following empty cell, use the given equation above (using numpy matrix operations) to find the values of the optimal vector $w$. You will need to be sure $X$ and $y$ are created like the instructor talked about in the video. Don't forget to include any modifications to $X$ to account for the bias term in $w$. You might be interested in the following functions:

- `import numpy as np`
- `np.hstack((mat1,mat2))` stack two matrices horizontally, to create a new matrix
- `np.ones((rows,cols))` create a matrix full of ones
- `my_mat.T` takes transpose of numpy matrix named `my_mat`
- `np.dot(mat1,mat2)` or `mat1 @ mat2` is matrix multiplication for two matrices
- `np.linalg.inv(mat)` gets the inverse of the variable `mat`

In [5]:
# Write you code here, print the values of the regression weights using the 'print()' function in python

# adding column of ones to X matrix
X = np.hstack((np.ones((ds.data.shape[0], 1)), ds.data))

y = ds.target.reshape(-1, 1)

# Calculate the regression weights (w)
w = np.linalg.inv(X.T @ X) @ X.T @ y

print("Optimal vector w:")
print(w)



Optimal vector w:
[[ 152.13348416]
 [ -10.0098663 ]
 [-239.81564367]
 [ 519.84592005]
 [ 324.3846455 ]
 [-792.17563855]
 [ 476.73902101]
 [ 101.04326794]
 [ 177.06323767]
 [ 751.27369956]
 [  67.62669218]]



___
<a id="sklearn"></a>
<a href="#top">Back to Top</a>
# Start of Live Session Coding

**Exercise 2:** Scikit-learn also has a linear regression fitting implementation. Look at the scikit learn API and learn to use the linear regression method. The API is here: 

- API Reference: http://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LinearRegression.html

Use the sklearn `LinearRegression` module to check your results from the previous question. 

**Question 2**: Did you get the same parameters? 

In [14]:
from sklearn.linear_model import LinearRegression

# write your code here, print the values of model by accessing 
#    its properties that you looked up from the API

# same info as previous question
X = np.hstack((np.ones((ds.data.shape[0], 1)), ds.data))
y = ds.target

reg = LinearRegression()

# Fit the model
reg.fit(X, y)


print('model coefficients are:', reg.coef_)
print('model intercept is', reg.intercept_)
print('Answer to question is', 'Yes, we got the same parameters')

model coefficients are: [   0.          -10.0098663  -239.81564367  519.84592005  324.3846455
 -792.17563855  476.73902101  101.04326794  177.06323767  751.27369956
   67.62669218]
model intercept is 152.13348416289597
Answer to question is Yes, we got the same parameters


________________________________________________________________________________________________________

Recall that to predict the output from our model, $\hat{y}$, from $w$ and $X$ we need to use the following formula:

- $\hat{y}=w^TX^T$, for row vector $\hat{y}$
- OR 
- $\hat{y}=Xw$, for column vector $\hat{y}$

Where $X$ is a matrix with example instances in *each row* of the matrix (and the bias term).

**Exercise 3:** 
- *Part A:* Use matrix multiplication to predict output using numpy, $\hat{y}_{numpy}$. 
 - **Note**: you may need to make the regression weights a column vector using the following code: `w = w.reshape((len(w),1))` This assumes your weights vector is assigned to the variable named `w`.
- *Part B:* Use the sklearn API to get the values for $\hat{y}_{sklearn}$ (hint: use the `.predict` function of the API).
- *Part C:* Calculate the mean squared error between your prediction from numpy and the target, $\frac{1}{M}\sum_i(y-\hat{y}_{numpy})^2$. 
- *Part D:* Calculate the mean squared error between your sklearn prediction and the target, $\frac{1}{M}\sum_i(y-\hat{y}_{sklearn})^2$.
 - **Note**: parts C and D can each be completed in one line of code using numpy. There is no need to write a `for` loop.

In [21]:
# Use this block to answer the questions

w = w.reshape((len(w),1)) # make w a column vector

# Part A using matrix multiplication using numpy
yhat_numpy = X @ w
yhat_numpy = yhat_numpy.flatten()

# Part B using sklearn
yhat_sklearn = reg.predict(X)

# Part C MSE between prediction from numpy and target
MSE_numpy = np.mean((y - yhat_numpy)**2)

# Part D MSE between prediction from sklearn and target
MSE_sklearn = np.mean((y - yhat_sklearn)**2)

print('MSE Sklearn is:', MSE_sklearn)
print('MSE Numpy is:', MSE_numpy)

MSE Sklearn is: 2859.6963475867506
MSE Numpy is: 2859.6963475867506


________________________________________________________________________________________________________
<a id="classification"></a>
<a href="#top">Back to Top</a>
## Using Linear Classification
Now lets use the code you created to make a classifier with linear boundaries. Run the following code in order to load the iris dataset.

In [8]:
from sklearn.datasets import load_iris
import numpy as np

# this will overwrite the diabetes dataset
ds = load_iris()
print('features shape:', ds.data.shape) # there are 150 instances and 4 features per instance
print('original number of classes:', len(np.unique(ds.target)))

# now let's make this a binary classification task
ds.target = ds.target>1
print ('new number of classes:', len(np.unique(ds.target)))

features shape: (150, 4)
original number of classes: 3
new number of classes: 2


________________________________________________________________________________________________________

**Exercise 4:** Now use linear regression to come up with a set of weights, `w`, that predict the class value. You can use numpy or sklearn, whichever you prefer. This is exactly like you did before for the *diabetes* dataset. However, instead of regressing to continuous values, you are just regressing to the integer value of the class (0 or 1), like we talked about in the video (using the hard limit function). 
 - **Note**: If you are using numpy, remember to account for the bias term when constructing the feature matrix, `X`.
 

In [9]:
# write your code here and print the values of the weights 

X = ds.data  
y = ds.target > 1

# Add bias term to X matrix
X_bias = np.c_[X, np.ones(X.shape[0])]  

# linear regression
reg = LinearRegression()
reg.fit(X_bias, y)

w = reg.coef_
b = reg.intercept_

# Print the weights of the linear classifier.
print('model coefficients are:', w)
print('model intercept is', b)

model coefficients are: [0. 0. 0. 0. 0.]
model intercept is 0.0


________________________________________________________________________________________________________

**Exercise 5:** Finally, use a hard decision function on the output of the linear regression to make this a binary classifier. This is just like we talked about in the video, where the output of the linear regression passes through a function: 

- $\hat{y}=g(w^TX^T)$ where
 - $g(w^TX^T)$ for $w^TX^T < \alpha$ maps the predicted class to `0` 
 - $g(w^TX^T)$ for $w^TX^T \geq \alpha$ maps the predicted class to `1`. 

Here, alpha is a threshold for deciding the class. 

**Question 3**: What value for $\alpha$ makes the most sense? What is the accuracy of the classifier given the $\alpha$ you chose? 

Note: You can calculate the accuracy with the following code: `accuracy = float(sum(yhat==y)) / len(y)` assuming you choose variable names `y` and `yhat` for the target and prediction, respectively.

In [10]:
# use this box to predict the classification output


alpha = 0.5 

# Hard decision function
def hard_decision(x, alpha):
    return np.where(x < alpha, 0, 1)

# Predict using the linear regression model
predict_continuous = np.dot(X_bias, w) + b
predict_binary = hard_decision(predict_continuous, alpha)

accuracy = float(np.sum(predict_binary == y)) / len(y)
percent_accuracy = accuracy * 100

print('Percentage accuracy:', percent_accuracy)

threshold_values = np.linspace(0, 1, 100)

best_accuracy = 0
best_alpha = None

# Iteratation to find best alpha
for alpha in threshold_values:
    predict_binary = hard_decision(predict_continuous, alpha) # hard decision function loop
    
    # Calculate accuracy
    accuracy = np.sum(predict_binary == y) / len(y)
    
    # Check threshold for better accuracy 
    if accuracy > best_accuracy:
        best_accuracy = accuracy
        best_alpha = alpha

print("Best alpha:", best_alpha)
print("Best accuracy:", best_accuracy * 100, "%")

Percentage accuracy: 100.0
Best alpha: 0.010101010101010102
Best accuracy: 100.0 %


________________________________________________________________________________________________________

That's all! Please **save (make sure you saved!!!) and upload your rendered notebook** and please include **team member names** in the notebook submission.